### ISSUE TITLE
Can't build - MacOSX (El Capitan)

### ISSUE THREAD

**Issue by stevefold** [WatchBeam/ftl-studio#60]
Hey there,

I'm having issues building this and cannot figure it out:

`Checking bin
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/bin/.gitignore': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/bin/.gitignore'", "'bin/.gitignore'")
("'rundir/RelWithDebInfo/bin/libobs-opengl.so'", "'bin/libobs-opengl.so'")
("'rundir/RelWithDebInfo/bin/libobs.0.dylib'", "'bin/libobs.0.dylib'")
("'rundir/RelWithDebInfo/bin/libobsglad.0.dylib'", "'bin/libobsglad.0.dylib'")
("'rundir/RelWithDebInfo/bin/tachyon'", "'bin/tachyon'")
Checking obs-plugins
("'rundir/RelWithDebInfo/obs-plugins/coreaudio-encoder.so'", "'obs-plugins/coreaudio-encoder.so'")
("'rundir/RelWithDebInfo/obs-plugins/image-source.so'", "'obs-plugins/image-source.so'")
("'rundir/RelWithDebInfo/obs-plugins/mac-avcapture.so'", "'obs-plugins/mac-avcapture.so'")
("'rundir/RelWithDebInfo/obs-plugins/mac-capture.so'", "'obs-plugins/mac-capture.so'")
("'rundir/RelWithDebInfo/obs-plugins/mac-decklink.so'", "'obs-plugins/mac-decklink.so'")
("'rundir/RelWithDebInfo/obs-plugins/mac-syphon.so'", "'obs-plugins/mac-syphon.so'")
("'rundir/RelWithDebInfo/obs-plugins/mac-vth264.so'", "'obs-plugins/mac-vth264.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-ffmpeg.so'", "'obs-plugins/obs-ffmpeg.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-filters.so'", "'obs-plugins/obs-filters.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-libfdk.so'", "'obs-plugins/obs-libfdk.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-outputs.so'", "'obs-plugins/obs-outputs.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-transitions.so'", "'obs-plugins/obs-transitions.so'")
("'rundir/RelWithDebInfo/obs-plugins/obs-x264.so'", "'obs-plugins/obs-x264.so'")
("'rundir/RelWithDebInfo/obs-plugins/rtmp-services.so'", "'obs-plugins/rtmp-services.so'")
("'rundir/RelWithDebInfo/obs-plugins/text-freetype2.so'", "'obs-plugins/text-freetype2.so'")
Checking data
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/.gitignore': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/.gitignore'", "'data/.gitignore'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/bicubic_scale.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/bicubic_scale.effect'", "'data/libobs/bicubic_scale.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/bilinear_lowres_scale.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/bilinear_lowres_scale.effect'", "'data/libobs/bilinear_lowres_scale.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/default.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/default.effect'", "'data/libobs/default.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/default_rect.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/default_rect.effect'", "'data/libobs/default_rect.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_base.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_base.effect'", "'data/libobs/deinterlace_base.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_blend.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_blend.effect'", "'data/libobs/deinterlace_blend.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_blend_2x.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_blend_2x.effect'", "'data/libobs/deinterlace_blend_2x.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_discard.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_discard.effect'", "'data/libobs/deinterlace_discard.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_discard_2x.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_discard_2x.effect'", "'data/libobs/deinterlace_discard_2x.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_linear.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_linear.effect'", "'data/libobs/deinterlace_linear.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_linear_2x.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_linear_2x.effect'", "'data/libobs/deinterlace_linear_2x.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_yadif.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_yadif.effect'", "'data/libobs/deinterlace_yadif.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/deinterlace_yadif_2x.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/deinterlace_yadif_2x.effect'", "'data/libobs/deinterlace_yadif_2x.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/format_conversion.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/format_conversion.effect'", "'data/libobs/format_conversion.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/lanczos_scale.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/lanczos_scale.effect'", "'data/libobs/lanczos_scale.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/opaque.effect': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
("'rundir/RelWithDebInfo/data/libobs/opaque.effect'", "'data/libobs/opaque.effect'")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/libobs/premultiplied_alpha.effect': The file was not recognized as a valid object file.`

......

`("'rundir/RelWithDebInfo/data/obs-studio/themes/Dark/updown.png'", "'data/obs-studio/themes/Dark/updown.png'")
('inspecting', "LibTarget(path='rundir/RelWithDebInfo/data/obs-studio/themes/Dark/updown.png', external=False, copy_as=None)")
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'rundir/RelWithDebInfo/data/obs-studio/themes/Dark/updown.png': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed
Traceback (most recent call last):
  File "build_app.py", line 102, in <module>
    universal_newlines=True)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'otool -L 'rundir/RelWithDebInfo/data/obs-studio/themes/Dark/updown.png'' returned non-zero exit status 1
`

Thanks!

**Comment by 7Ds7** [comment]
I am getting the same for macOS Sierra
together with the above and some deprecated warnings it finishes like this, without finding. the.app

` File "build_app.py", line 102, in <module>
    universal_newlines=True)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'otool -L 'rundir/RelWithDebInfo/data/obs-studio/themes/Dark/updown.png'' returned non-zero exit status 1
chown: Tachyon.app: No such file or directory
@@ Archiving build to DMG...
...............................................................................
created: /Users/glitch/MyStuff/tachyon/build/Tachyon.dmg
/dev/disk2          	GUID_partition_scheme
/dev/disk2s1        	Apple_HFS                      	/Volumes/Tachyon Install
cp: ./Tachyon.app: No such file or directory
"/Volumes/Tachyon Install" unmounted successfully.`
